### ISSUE TITLE
Missing LICENSE File

### ISSUE THREAD

**Issue by MTecknology** [bsm/redeo#14]
You have a copy of a license in your README file, but you do not include an actual LICENSE file. A license should typically be it's own file and not included as part of the documentation. Would you be willing to fix this so that I can continue getting this source (ultimately Gitea) into Debian?

**Comment by dim** [comment]
Hey, I am currently working on a [v2](https://github.com/bsm/redeo/tree/feature/v2) which is due soon. I will update it there

**Comment by MTecknology** [comment]
I've provided a very simple patch that addresses my concerns. It is against the master branch because this is change should be separate of v2. If this isn't cherry picked for v1, that's fine, but I'm currently stuck until I can provide an actual LICENSE file from this repository.
